export const LIVE_GAMES = 'LIVE_GAMES'
export const LIVE_GAMES_BY_DATE = 'LIVE_GAMES_BY_DATE'
export const LEAGUES = 'LEAGUES'

export const ODDS = 'ODDS'
export const PREDICTION_LIVE_GAMES = 'PREDICTION_LIVE_GAMES'
export const PREDICTION_LEAGUES = 'PREDICTION_LEAGUES'

export const ROOM_DATA = 'ROOM_DATA'
