export const LIVE_GAMES = 'LIVE_GAMES'
export const LIVE_GAMES_BY_DATE = 'LIVE_GAMES_BY_DATE'
export const LEAGUES = 'LEAGUES'

export const ODDS = 'ODDS'
export const PREDICTION_LIVE_GAMES = 'PREDICTION_LIVE_GAMES'
export const PREDICTION_LEAGUES = 'PREDICTION_LEAGUES'

export const ROOM_CODE = 'ROOM_CODE'
export const ROOM_GAME = 'ROOM_GAME'
export const USER_DATA = 'USER_DATA'
export const LOGIN = 'LOGIN'
export const SET_ROOM_DATA = 'SET_ROOM_DATA'
export const SET_POINTS = 'SET_POINTS'
export const GAME_DATA = 'GAME_DATA'
export const CLEAN_STATE = 'CLEAN_STATE'


export const LOADING_PREDICTION = 'LOADING_PREDICTION'
export const LOADING_LIVESCORE = 'LOADING_LIVESCORE'